In this notebook, you will learn how to manipulate data with Pytorch  
Let's start by importing Pytorch

In [155]:
import torch

## Basic tensor operation

In [156]:
tensor = torch.rand((4, 3, 2))
tensor

tensor([[[0.0627, 0.3620],
         [0.2407, 0.9065],
         [0.6188, 0.2378]],

        [[0.8487, 0.1538],
         [0.7839, 0.9753],
         [0.2453, 0.0294]],

        [[0.3489, 0.8594],
         [0.5224, 0.5241],
         [0.2523, 0.0329]],

        [[0.6125, 0.3861],
         [0.4003, 0.7517],
         [0.7151, 0.4329]]])

Display the size of the produced tensor

In [157]:
tensor.shape # or tensor.size()

torch.Size([4, 3, 2])

Give the total number of elements inside the tensor

In [158]:
tensor.numel()

24

Change the shape of the tensor into a 4x6 tensor

In [159]:
reshaped = tensor.reshape((4, 6))

reshaped.shape

torch.Size([4, 6])

Transform a python list into a tensor

In [160]:
list_to_transform = [[9, 8, 7], [4, 5, 6], [3, 2, 1]]

tensor = torch.tensor(list_to_transform)
tensor

tensor([[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]])

## Operations on tensor

In [161]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

Add 3 to every element of the tensor, put the result in a new tensor

In [162]:
y = x + 3

print('x = ', x)
print('y = ', y)

x =  tensor([0, 1, 2, 3])
y =  tensor([3, 4, 5, 6])


Multiply by 3 the tensor x, put the result in a new tensor

In [163]:
y = x * 3
y

tensor([0, 3, 6, 9])

Put every element of x to the power of 3

In [164]:
y = x**3
y

tensor([ 0,  1,  8, 27])

Multiply x with k

In [165]:
k = torch.Tensor([8, 7, 5, 1])

y = x * k
y

tensor([ 0.,  7., 10.,  3.])

Makes x to the power of k

In [166]:
y = x**k
y

tensor([ 0.,  1., 32.,  3.])

Put every element of x to exponential

In [167]:
y = torch.exp(x)
y

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

Perform the element wise product of `a` and `b`

In [168]:
a = torch.rand((5))
b = torch.rand((5))

y = a * b
y

tensor([0.6429, 0.0410, 0.0062, 0.3311, 0.0078])

Perform the dot product of `a` and `b`

In [169]:
y = torch.dot(a, b)
y

tensor(1.0289)

Sum along the column axis of `l`

In [170]:
l = torch.rand((5, 3, 6))
l.sum(dim=1, keepdim=True)

#l = torch.arange(5*3*6).reshape((5,3,6))
#for i in range(3):
#  print('\ndim = {}'.format(i))
#  summed = l.sum(dim=i, keepdim=True)
#  print(summed.shape)
#  print(summed)

tensor([[[1.4400, 1.0100, 2.0576, 1.9024, 1.4904, 1.7117]],

        [[1.1935, 0.9887, 1.6705, 0.5578, 0.3832, 1.5845]],

        [[2.1309, 2.0616, 1.8412, 0.9616, 1.8018, 0.6579]],

        [[1.5291, 2.5995, 1.4118, 1.1597, 1.8950, 1.6581]],

        [[1.7023, 1.6271, 0.1694, 1.5283, 0.8321, 1.9317]]])

## Slicing

Display the 3 last element of x

In [171]:
x[-3:]

tensor([1, 2, 3])

Display the last element of x

In [172]:
x[-1]

tensor(3)

Display the element of m, by step of 2

In [173]:
m = torch.arange(18)

m[::2] # = m[0::2] = m[0:-1:2]

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

Print only the first 2 rows of `matrix`

In [174]:
matrix = torch.arange(6*4*2).reshape(6,4,2) #torch.rand((6, 4, 2))

matrix[0:2]

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]])

Now, only print the first 2 columns of `matrix`

In [175]:
matrix[:,0:2]

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 8,  9],
         [10, 11]],

        [[16, 17],
         [18, 19]],

        [[24, 25],
         [26, 27]],

        [[32, 33],
         [34, 35]],

        [[40, 41],
         [42, 43]]])